// <auto-generated />
namespace HMS.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class patientsage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patientsage));
        
        string IMigrationMetadata.Id
        {
            get { return "202103070238127_patientsage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
