// <auto-generated />
namespace HMS.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class amountpaidinvoices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(amountpaidinvoices));
        
        string IMigrationMetadata.Id
        {
            get { return "202101201328287_amountpaidinvoices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
