// <auto-generated />
namespace HMS.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class invoicetransactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(invoicetransactions));
        
        string IMigrationMetadata.Id
        {
            get { return "202102010834539_invoicetransactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
