// <auto-generated />
namespace HMS.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class patientvalidationadharid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patientvalidationadharid));
        
        string IMigrationMetadata.Id
        {
            get { return "202101131200249_patient-validation-adharid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
